# Gnuplot script file for plotting a *.ene file generated by mercuryDPM
# run via: gnuplot -e "filename='name_of_file.ene'" energy.p

plot filename every ::1 using 1:2 with lines title 'Gravitational' , \
	filename every ::1 using 1:3 with lines title 'Kinetic' , \
	filename every ::1 using 1:4 with lines title 'Rotational' , \
	filename every ::1 using 1:5 with lines title 'Elastic' , \
	filename every ::1 using 1:($2+$3+$4+$5) with lines title 'Total'

set terminal pdf
set output "output.pdf"
replot

